version: '3.8'

services:

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: pokemon_user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pokemon-service:
    image: bankaya-challenge-service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pokemon_db
      SPRING_DATASOURCE_USERNAME: pokemon_user
      SPRING_DATASOURCE_PASSWORD: password123
    depends_on:
      - postgres

volumes:
  postgres_data:
